## Numpy Basics:--
NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed.

In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3]) 
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
# more than one dimensions 

a = np.array([[1, 2], [3, 4]]) 
print(a)
print("Shape: ",a.shape)

[[1 2]
 [3 4]]
Shape:  (2, 2)


In [10]:
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print (a)

[[1 2 3 4 5]]


In [11]:
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [13]:
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print (b)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
# an array of evenly spaced numbers  
a = np.arange(24) 
print (a)
print(a.ndim)

# now reshape it 
b = a.reshape(2,4,3) 
print (b) 
# b is having three dimensions

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [22]:
#Zeroes matrix

x = np.zeros((5,), dtype=np.int) 
print (x)

[0 0 0 0 0]


In [24]:

x = np.arange(10,20,2) #with stepsize of 2
print (x)

[10 12 14 16 18]


In [25]:
#Slicing

a = np.arange(10) 
s = slice(2,7,2) 
print (a[s])

[2 4 6]


In [27]:
a = np.arange(10) 
b = a[2:7:2] 
print(b)

[2 4 6]


In [30]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]') 
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [31]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

# this returns array of items in the second column 
print ('The items in the second column are:')  
print (a[...,1]) 
print ('\n')  

# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (a[1,...]) 
print ('\n')  

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [33]:
#Boolean array indexing

x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print('Our array is:') 
print(x) 
print('\n')  

# Now we will print the items greater than 5 
print('The items greater than 5 are:') 
print(x[x > 5])

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:
[ 6  7  8  9 10 11]


In [34]:
#Transposing and modifying the array

a = np.arange(0,60,5) 
a = a.reshape(3,4) 
   
print('Original array is:')
print(a) 
print('\n')  
   
print('Transpose of the original array is:' )
b = a.T 
print(b) 
print('\n')  
   
print('Modified array is:') 
for x in np.nditer(b): 
   print(x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55
